enum actionTypes {
    FETCH_ALL_POSTS = 'FETCH ALL POSTS',
    CREATE_POST = 'CREATE POST',
    UPDATE_CURRENT_ID = 'UPDATE CURRENT ID',
    UPDATE_POST = 'UPDATE POST',
    DELETE_POST = 'DELETE_POST'
}

export default actionTypes;
